name: Code Format Check

on:
  push:
    branches: [ main ]
    paths:
      - 'cmake/**'
      - 'cpp/**'
      - 'platforms/**'
      - 'vcpkg/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'vcpkg-configuration.json'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'cmake/**'
      - 'cpp/**'
      - 'platforms/**'
      - 'vcpkg/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'vcpkg.json'
      - 'vcpkg-configuration.json'
      - '.github/workflows/**'

jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DoozyX/clang-format-lint-action@v0.20
        with:
          source: 'cpp linux windows android/cpp'
          extensions: 'cpp,cc,h,hpp,inc'
          clangFormatVersion: 20